language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - travis_retry php composer.phar install --dev --no-interaction --prefer-source

script:
  - bin/phpunit
  - src/EPV.php run --debug --github="nickvergessen/phpbb-ext-acme-demo"

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email:
    recipients:
      - paul999@phpbb.com
    on_success: change
    on_failure: change
